//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualChefApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int IngredientId { get; set; }
        public string IngredientName { get; set; }
        public string ImageUrl { get; set; }
        public string Nutritions { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
