//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DatabaseFirst.VirtualChefModel", "FK_Categories_To_Ingredients", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualChefApi.Category), "Ingredients", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualChefApi.Ingredient), true)]
[assembly: EdmRelationshipAttribute("DatabaseFirst.VirtualChefModel", "FK_Ingredients_To_Cook", "Ingredients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualChefApi.Ingredient), "Cook", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualChefApi.Cook), true)]
[assembly: EdmRelationshipAttribute("DatabaseFirst.VirtualChefModel", "FK_Recipe", "Recipes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualChefApi.Recipe), "Cook", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualChefApi.Cook), true)]
[assembly: EdmRelationshipAttribute("DatabaseFirst.VirtualChefModel", "FK_To_Country", "Countries", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualChefApi.Country), "Recipes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualChefApi.Recipe), true)]
[assembly: EdmRelationshipAttribute("DatabaseFirst.VirtualChefModel", "FK_To_Diet", "Diet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualChefApi.Diet), "Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualChefApi.Menu), true)]
[assembly: EdmRelationshipAttribute("DatabaseFirst.VirtualChefModel", "FK_Menu_To_Restaurants", "Restaurants", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualChefApi.Restaurant), "Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualChefApi.Menu), true)]
[assembly: EdmRelationshipAttribute("DatabaseFirst.VirtualChefModel", "MenuRecipes", "Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualChefApi.Menu), "Recipes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualChefApi.Recipe))]

#endregion

namespace VirtualChefApi
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VirtualChefContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VirtualChefContext object using the connection string found in the 'VirtualChefContext' section of the application configuration file.
        /// </summary>
        public VirtualChefContext() : base("name=VirtualChefContext", "VirtualChefContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VirtualChefContext object.
        /// </summary>
        public VirtualChefContext(string connectionString) : base(connectionString, "VirtualChefContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VirtualChefContext object.
        /// </summary>
        public VirtualChefContext(EntityConnection connection) : base(connection, "VirtualChefContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cook> Cooks
        {
            get
            {
                if ((_Cooks == null))
                {
                    _Cooks = base.CreateObjectSet<Cook>("Cooks");
                }
                return _Cooks;
            }
        }
        private ObjectSet<Cook> _Cooks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Country> Countries
        {
            get
            {
                if ((_Countries == null))
                {
                    _Countries = base.CreateObjectSet<Country>("Countries");
                }
                return _Countries;
            }
        }
        private ObjectSet<Country> _Countries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Diet> Diets
        {
            get
            {
                if ((_Diets == null))
                {
                    _Diets = base.CreateObjectSet<Diet>("Diets");
                }
                return _Diets;
            }
        }
        private ObjectSet<Diet> _Diets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredient> Ingredients
        {
            get
            {
                if ((_Ingredients == null))
                {
                    _Ingredients = base.CreateObjectSet<Ingredient>("Ingredients");
                }
                return _Ingredients;
            }
        }
        private ObjectSet<Ingredient> _Ingredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Menu> Menus
        {
            get
            {
                if ((_Menus == null))
                {
                    _Menus = base.CreateObjectSet<Menu>("Menus");
                }
                return _Menus;
            }
        }
        private ObjectSet<Menu> _Menus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Recipe> Recipes
        {
            get
            {
                if ((_Recipes == null))
                {
                    _Recipes = base.CreateObjectSet<Recipe>("Recipes");
                }
                return _Recipes;
            }
        }
        private ObjectSet<Recipe> _Recipes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Restaurant> Restaurants
        {
            get
            {
                if ((_Restaurants == null))
                {
                    _Restaurants = base.CreateObjectSet<Restaurant>("Restaurants");
                }
                return _Restaurants;
            }
        }
        private ObjectSet<Restaurant> _Restaurants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cooks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCooks(Cook cook)
        {
            base.AddObject("Cooks", cook);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Countries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCountries(Country country)
        {
            base.AddObject("Countries", country);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Diets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDiets(Diet diet)
        {
            base.AddObject("Diets", diet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients(Ingredient ingredient)
        {
            base.AddObject("Ingredients", ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Menus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenus(Menu menu)
        {
            base.AddObject("Menus", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Recipes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipes(Recipe recipe)
        {
            base.AddObject("Recipes", recipe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Restaurants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRestaurants(Restaurant restaurant)
        {
            base.AddObject("Restaurants", restaurant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseFirst.VirtualChefModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="categoryName">Initial value of the CategoryName property.</param>
        /// <param name="imageUrl">Initial value of the ImageUrl property.</param>
        public static Category CreateCategory(global::System.Int32 categoryId, global::System.String categoryName, global::System.String imageUrl)
        {
            Category category = new Category();
            category.CategoryId = categoryId;
            category.CategoryName = categoryName;
            category.ImageUrl = imageUrl;
            return category;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                if (_CategoryId != value)
                {
                    OnCategoryIdChanging(value);
                    ReportPropertyChanging("CategoryId");
                    _CategoryId = StructuralObject.SetValidValue(value, "CategoryId");
                    ReportPropertyChanged("CategoryId");
                    OnCategoryIdChanged();
                }
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, false, "CategoryName");
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, false, "ImageUrl");
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_Categories_To_Ingredients", "Ingredients")]
        public EntityCollection<Ingredient> Ingredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingredient>("DatabaseFirst.VirtualChefModel.FK_Categories_To_Ingredients", "Ingredients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingredient>("DatabaseFirst.VirtualChefModel.FK_Categories_To_Ingredients", "Ingredients", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseFirst.VirtualChefModel", Name="Cook")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cook : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cook object.
        /// </summary>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="ingredientId">Initial value of the IngredientId property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="measurement">Initial value of the Measurement property.</param>
        public static Cook CreateCook(global::System.Int32 recipeId, global::System.Int32 ingredientId, global::System.Decimal quantity, global::System.String measurement)
        {
            Cook cook = new Cook();
            cook.RecipeId = recipeId;
            cook.IngredientId = ingredientId;
            cook.Quantity = quantity;
            cook.Measurement = measurement;
            return cook;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                if (_RecipeId != value)
                {
                    OnRecipeIdChanging(value);
                    ReportPropertyChanging("RecipeId");
                    _RecipeId = StructuralObject.SetValidValue(value, "RecipeId");
                    ReportPropertyChanged("RecipeId");
                    OnRecipeIdChanged();
                }
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientId
        {
            get
            {
                return _IngredientId;
            }
            set
            {
                if (_IngredientId != value)
                {
                    OnIngredientIdChanging(value);
                    ReportPropertyChanging("IngredientId");
                    _IngredientId = StructuralObject.SetValidValue(value, "IngredientId");
                    ReportPropertyChanged("IngredientId");
                    OnIngredientIdChanged();
                }
            }
        }
        private global::System.Int32 _IngredientId;
        partial void OnIngredientIdChanging(global::System.Int32 value);
        partial void OnIngredientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value, "Quantity");
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Decimal _Quantity;
        partial void OnQuantityChanging(global::System.Decimal value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Measurement
        {
            get
            {
                return _Measurement;
            }
            set
            {
                OnMeasurementChanging(value);
                ReportPropertyChanging("Measurement");
                _Measurement = StructuralObject.SetValidValue(value, false, "Measurement");
                ReportPropertyChanged("Measurement");
                OnMeasurementChanged();
            }
        }
        private global::System.String _Measurement;
        partial void OnMeasurementChanging(global::System.String value);
        partial void OnMeasurementChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_Ingredients_To_Cook", "Ingredients")]
        public Ingredient Ingredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("DatabaseFirst.VirtualChefModel.FK_Ingredients_To_Cook", "Ingredients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("DatabaseFirst.VirtualChefModel.FK_Ingredients_To_Cook", "Ingredients").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ingredient> IngredientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("DatabaseFirst.VirtualChefModel.FK_Ingredients_To_Cook", "Ingredients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ingredient>("DatabaseFirst.VirtualChefModel.FK_Ingredients_To_Cook", "Ingredients", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_Recipe", "Recipes")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("DatabaseFirst.VirtualChefModel.FK_Recipe", "Recipes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("DatabaseFirst.VirtualChefModel.FK_Recipe", "Recipes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("DatabaseFirst.VirtualChefModel.FK_Recipe", "Recipes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("DatabaseFirst.VirtualChefModel.FK_Recipe", "Recipes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseFirst.VirtualChefModel", Name="Country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Country : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Country object.
        /// </summary>
        /// <param name="countryId">Initial value of the CountryId property.</param>
        /// <param name="countryName">Initial value of the CountryName property.</param>
        public static Country CreateCountry(global::System.String countryId, global::System.String countryName)
        {
            Country country = new Country();
            country.CountryId = countryId;
            country.CountryName = countryName;
            return country;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CountryId
        {
            get
            {
                return _CountryId;
            }
            set
            {
                if (_CountryId != value)
                {
                    OnCountryIdChanging(value);
                    ReportPropertyChanging("CountryId");
                    _CountryId = StructuralObject.SetValidValue(value, false, "CountryId");
                    ReportPropertyChanged("CountryId");
                    OnCountryIdChanged();
                }
            }
        }
        private global::System.String _CountryId;
        partial void OnCountryIdChanging(global::System.String value);
        partial void OnCountryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CountryName
        {
            get
            {
                return _CountryName;
            }
            set
            {
                OnCountryNameChanging(value);
                ReportPropertyChanging("CountryName");
                _CountryName = StructuralObject.SetValidValue(value, false, "CountryName");
                ReportPropertyChanged("CountryName");
                OnCountryNameChanged();
            }
        }
        private global::System.String _CountryName;
        partial void OnCountryNameChanging(global::System.String value);
        partial void OnCountryNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_To_Country", "Recipes")]
        public EntityCollection<Recipe> Recipes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recipe>("DatabaseFirst.VirtualChefModel.FK_To_Country", "Recipes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recipe>("DatabaseFirst.VirtualChefModel.FK_To_Country", "Recipes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseFirst.VirtualChefModel", Name="Diet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Diet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Diet object.
        /// </summary>
        /// <param name="dietId">Initial value of the DietId property.</param>
        /// <param name="dietName">Initial value of the DietName property.</param>
        public static Diet CreateDiet(global::System.Int32 dietId, global::System.String dietName)
        {
            Diet diet = new Diet();
            diet.DietId = dietId;
            diet.DietName = dietName;
            return diet;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DietId
        {
            get
            {
                return _DietId;
            }
            set
            {
                if (_DietId != value)
                {
                    OnDietIdChanging(value);
                    ReportPropertyChanging("DietId");
                    _DietId = StructuralObject.SetValidValue(value, "DietId");
                    ReportPropertyChanged("DietId");
                    OnDietIdChanged();
                }
            }
        }
        private global::System.Int32 _DietId;
        partial void OnDietIdChanging(global::System.Int32 value);
        partial void OnDietIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DietName
        {
            get
            {
                return _DietName;
            }
            set
            {
                OnDietNameChanging(value);
                ReportPropertyChanging("DietName");
                _DietName = StructuralObject.SetValidValue(value, false, "DietName");
                ReportPropertyChanged("DietName");
                OnDietNameChanged();
            }
        }
        private global::System.String _DietName;
        partial void OnDietNameChanging(global::System.String value);
        partial void OnDietNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_To_Diet", "Menu")]
        public EntityCollection<Menu> Menus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Menu>("DatabaseFirst.VirtualChefModel.FK_To_Diet", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Menu>("DatabaseFirst.VirtualChefModel.FK_To_Diet", "Menu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseFirst.VirtualChefModel", Name="Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredient object.
        /// </summary>
        /// <param name="ingredientId">Initial value of the IngredientId property.</param>
        /// <param name="ingredientName">Initial value of the IngredientName property.</param>
        /// <param name="imageUrl">Initial value of the ImageUrl property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        public static Ingredient CreateIngredient(global::System.Int32 ingredientId, global::System.String ingredientName, global::System.String imageUrl, global::System.Int32 categoryId)
        {
            Ingredient ingredient = new Ingredient();
            ingredient.IngredientId = ingredientId;
            ingredient.IngredientName = ingredientName;
            ingredient.ImageUrl = imageUrl;
            ingredient.CategoryId = categoryId;
            return ingredient;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientId
        {
            get
            {
                return _IngredientId;
            }
            set
            {
                if (_IngredientId != value)
                {
                    OnIngredientIdChanging(value);
                    ReportPropertyChanging("IngredientId");
                    _IngredientId = StructuralObject.SetValidValue(value, "IngredientId");
                    ReportPropertyChanged("IngredientId");
                    OnIngredientIdChanged();
                }
            }
        }
        private global::System.Int32 _IngredientId;
        partial void OnIngredientIdChanging(global::System.Int32 value);
        partial void OnIngredientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IngredientName
        {
            get
            {
                return _IngredientName;
            }
            set
            {
                OnIngredientNameChanging(value);
                ReportPropertyChanging("IngredientName");
                _IngredientName = StructuralObject.SetValidValue(value, false, "IngredientName");
                ReportPropertyChanged("IngredientName");
                OnIngredientNameChanged();
            }
        }
        private global::System.String _IngredientName;
        partial void OnIngredientNameChanging(global::System.String value);
        partial void OnIngredientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, false, "ImageUrl");
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nutritions
        {
            get
            {
                return _Nutritions;
            }
            set
            {
                OnNutritionsChanging(value);
                ReportPropertyChanging("Nutritions");
                _Nutritions = StructuralObject.SetValidValue(value, true, "Nutritions");
                ReportPropertyChanged("Nutritions");
                OnNutritionsChanged();
            }
        }
        private global::System.String _Nutritions;
        partial void OnNutritionsChanging(global::System.String value);
        partial void OnNutritionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value, "CategoryId");
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_Categories_To_Ingredients", "Categories")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("DatabaseFirst.VirtualChefModel.FK_Categories_To_Ingredients", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("DatabaseFirst.VirtualChefModel.FK_Categories_To_Ingredients", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("DatabaseFirst.VirtualChefModel.FK_Categories_To_Ingredients", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("DatabaseFirst.VirtualChefModel.FK_Categories_To_Ingredients", "Categories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_Ingredients_To_Cook", "Cook")]
        public EntityCollection<Cook> Cooks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cook>("DatabaseFirst.VirtualChefModel.FK_Ingredients_To_Cook", "Cook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cook>("DatabaseFirst.VirtualChefModel.FK_Ingredients_To_Cook", "Cook", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseFirst.VirtualChefModel", Name="Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Menu object.
        /// </summary>
        /// <param name="menuId">Initial value of the MenuId property.</param>
        /// <param name="menuName">Initial value of the MenuName property.</param>
        /// <param name="imagerUrl">Initial value of the ImagerUrl property.</param>
        /// <param name="dietId">Initial value of the DietId property.</param>
        /// <param name="restaurantId">Initial value of the RestaurantId property.</param>
        public static Menu CreateMenu(global::System.Int32 menuId, global::System.String menuName, global::System.String imagerUrl, global::System.Int32 dietId, global::System.Int32 restaurantId)
        {
            Menu menu = new Menu();
            menu.MenuId = menuId;
            menu.MenuName = menuName;
            menu.ImagerUrl = imagerUrl;
            menu.DietId = dietId;
            menu.RestaurantId = restaurantId;
            return menu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MenuId
        {
            get
            {
                return _MenuId;
            }
            set
            {
                if (_MenuId != value)
                {
                    OnMenuIdChanging(value);
                    ReportPropertyChanging("MenuId");
                    _MenuId = StructuralObject.SetValidValue(value, "MenuId");
                    ReportPropertyChanged("MenuId");
                    OnMenuIdChanged();
                }
            }
        }
        private global::System.Int32 _MenuId;
        partial void OnMenuIdChanging(global::System.Int32 value);
        partial void OnMenuIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MenuName
        {
            get
            {
                return _MenuName;
            }
            set
            {
                OnMenuNameChanging(value);
                ReportPropertyChanging("MenuName");
                _MenuName = StructuralObject.SetValidValue(value, false, "MenuName");
                ReportPropertyChanged("MenuName");
                OnMenuNameChanged();
            }
        }
        private global::System.String _MenuName;
        partial void OnMenuNameChanging(global::System.String value);
        partial void OnMenuNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImagerUrl
        {
            get
            {
                return _ImagerUrl;
            }
            set
            {
                OnImagerUrlChanging(value);
                ReportPropertyChanging("ImagerUrl");
                _ImagerUrl = StructuralObject.SetValidValue(value, false, "ImagerUrl");
                ReportPropertyChanged("ImagerUrl");
                OnImagerUrlChanged();
            }
        }
        private global::System.String _ImagerUrl;
        partial void OnImagerUrlChanging(global::System.String value);
        partial void OnImagerUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DietId
        {
            get
            {
                return _DietId;
            }
            set
            {
                OnDietIdChanging(value);
                ReportPropertyChanging("DietId");
                _DietId = StructuralObject.SetValidValue(value, "DietId");
                ReportPropertyChanged("DietId");
                OnDietIdChanged();
            }
        }
        private global::System.Int32 _DietId;
        partial void OnDietIdChanging(global::System.Int32 value);
        partial void OnDietIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RestaurantId
        {
            get
            {
                return _RestaurantId;
            }
            set
            {
                OnRestaurantIdChanging(value);
                ReportPropertyChanging("RestaurantId");
                _RestaurantId = StructuralObject.SetValidValue(value, "RestaurantId");
                ReportPropertyChanged("RestaurantId");
                OnRestaurantIdChanged();
            }
        }
        private global::System.Int32 _RestaurantId;
        partial void OnRestaurantIdChanging(global::System.Int32 value);
        partial void OnRestaurantIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_To_Diet", "Diet")]
        public Diet Diet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Diet>("DatabaseFirst.VirtualChefModel.FK_To_Diet", "Diet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Diet>("DatabaseFirst.VirtualChefModel.FK_To_Diet", "Diet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Diet> DietReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Diet>("DatabaseFirst.VirtualChefModel.FK_To_Diet", "Diet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Diet>("DatabaseFirst.VirtualChefModel.FK_To_Diet", "Diet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_Menu_To_Restaurants", "Restaurants")]
        public Restaurant Restaurant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurant>("DatabaseFirst.VirtualChefModel.FK_Menu_To_Restaurants", "Restaurants").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurant>("DatabaseFirst.VirtualChefModel.FK_Menu_To_Restaurants", "Restaurants").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Restaurant> RestaurantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurant>("DatabaseFirst.VirtualChefModel.FK_Menu_To_Restaurants", "Restaurants");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Restaurant>("DatabaseFirst.VirtualChefModel.FK_Menu_To_Restaurants", "Restaurants", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "MenuRecipes", "Recipes")]
        public EntityCollection<Recipe> Recipes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Recipe>("DatabaseFirst.VirtualChefModel.MenuRecipes", "Recipes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Recipe>("DatabaseFirst.VirtualChefModel.MenuRecipes", "Recipes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseFirst.VirtualChefModel", Name="Recipe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recipe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Recipe object.
        /// </summary>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="recipeName">Initial value of the RecipeName property.</param>
        /// <param name="directions">Initial value of the Directions property.</param>
        /// <param name="preptime">Initial value of the Preptime property.</param>
        /// <param name="cookTime">Initial value of the CookTime property.</param>
        /// <param name="readyIn">Initial value of the ReadyIn property.</param>
        /// <param name="author">Initial value of the Author property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="countryId">Initial value of the CountryId property.</param>
        public static Recipe CreateRecipe(global::System.Int32 recipeId, global::System.String recipeName, global::System.String directions, global::System.TimeSpan preptime, global::System.TimeSpan cookTime, global::System.TimeSpan readyIn, global::System.String author, global::System.DateTime createDate, global::System.String countryId)
        {
            Recipe recipe = new Recipe();
            recipe.RecipeId = recipeId;
            recipe.RecipeName = recipeName;
            recipe.Directions = directions;
            recipe.Preptime = preptime;
            recipe.CookTime = cookTime;
            recipe.ReadyIn = readyIn;
            recipe.Author = author;
            recipe.CreateDate = createDate;
            recipe.CountryId = countryId;
            return recipe;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                if (_RecipeId != value)
                {
                    OnRecipeIdChanging(value);
                    ReportPropertyChanging("RecipeId");
                    _RecipeId = StructuralObject.SetValidValue(value, "RecipeId");
                    ReportPropertyChanged("RecipeId");
                    OnRecipeIdChanged();
                }
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecipeName
        {
            get
            {
                return _RecipeName;
            }
            set
            {
                OnRecipeNameChanging(value);
                ReportPropertyChanging("RecipeName");
                _RecipeName = StructuralObject.SetValidValue(value, false, "RecipeName");
                ReportPropertyChanged("RecipeName");
                OnRecipeNameChanged();
            }
        }
        private global::System.String _RecipeName;
        partial void OnRecipeNameChanging(global::System.String value);
        partial void OnRecipeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Directions
        {
            get
            {
                return _Directions;
            }
            set
            {
                OnDirectionsChanging(value);
                ReportPropertyChanging("Directions");
                _Directions = StructuralObject.SetValidValue(value, false, "Directions");
                ReportPropertyChanged("Directions");
                OnDirectionsChanged();
            }
        }
        private global::System.String _Directions;
        partial void OnDirectionsChanging(global::System.String value);
        partial void OnDirectionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Preptime
        {
            get
            {
                return _Preptime;
            }
            set
            {
                OnPreptimeChanging(value);
                ReportPropertyChanging("Preptime");
                _Preptime = StructuralObject.SetValidValue(value, "Preptime");
                ReportPropertyChanged("Preptime");
                OnPreptimeChanged();
            }
        }
        private global::System.TimeSpan _Preptime;
        partial void OnPreptimeChanging(global::System.TimeSpan value);
        partial void OnPreptimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan CookTime
        {
            get
            {
                return _CookTime;
            }
            set
            {
                OnCookTimeChanging(value);
                ReportPropertyChanging("CookTime");
                _CookTime = StructuralObject.SetValidValue(value, "CookTime");
                ReportPropertyChanged("CookTime");
                OnCookTimeChanged();
            }
        }
        private global::System.TimeSpan _CookTime;
        partial void OnCookTimeChanging(global::System.TimeSpan value);
        partial void OnCookTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan ReadyIn
        {
            get
            {
                return _ReadyIn;
            }
            set
            {
                OnReadyInChanging(value);
                ReportPropertyChanging("ReadyIn");
                _ReadyIn = StructuralObject.SetValidValue(value, "ReadyIn");
                ReportPropertyChanged("ReadyIn");
                OnReadyInChanged();
            }
        }
        private global::System.TimeSpan _ReadyIn;
        partial void OnReadyInChanging(global::System.TimeSpan value);
        partial void OnReadyInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, false, "Author");
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value, "CreateDate");
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CountryId
        {
            get
            {
                return _CountryId;
            }
            set
            {
                OnCountryIdChanging(value);
                ReportPropertyChanging("CountryId");
                _CountryId = StructuralObject.SetValidValue(value, false, "CountryId");
                ReportPropertyChanged("CountryId");
                OnCountryIdChanged();
            }
        }
        private global::System.String _CountryId;
        partial void OnCountryIdChanging(global::System.String value);
        partial void OnCountryIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_Recipe", "Cook")]
        public EntityCollection<Cook> Cooks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cook>("DatabaseFirst.VirtualChefModel.FK_Recipe", "Cook");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cook>("DatabaseFirst.VirtualChefModel.FK_Recipe", "Cook", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_To_Country", "Countries")]
        public Country Country
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("DatabaseFirst.VirtualChefModel.FK_To_Country", "Countries").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("DatabaseFirst.VirtualChefModel.FK_To_Country", "Countries").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Country> CountryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("DatabaseFirst.VirtualChefModel.FK_To_Country", "Countries");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Country>("DatabaseFirst.VirtualChefModel.FK_To_Country", "Countries", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "MenuRecipes", "Menu")]
        public EntityCollection<Menu> Menus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Menu>("DatabaseFirst.VirtualChefModel.MenuRecipes", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Menu>("DatabaseFirst.VirtualChefModel.MenuRecipes", "Menu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseFirst.VirtualChefModel", Name="Restaurant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Restaurant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Restaurant object.
        /// </summary>
        /// <param name="restaurantId">Initial value of the RestaurantId property.</param>
        /// <param name="restaurantName">Initial value of the RestaurantName property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="gPSCoordinate">Initial value of the GPSCoordinate property.</param>
        public static Restaurant CreateRestaurant(global::System.Int32 restaurantId, global::System.String restaurantName, global::System.String address, global::System.String gPSCoordinate)
        {
            Restaurant restaurant = new Restaurant();
            restaurant.RestaurantId = restaurantId;
            restaurant.RestaurantName = restaurantName;
            restaurant.Address = address;
            restaurant.GPSCoordinate = gPSCoordinate;
            return restaurant;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RestaurantId
        {
            get
            {
                return _RestaurantId;
            }
            set
            {
                if (_RestaurantId != value)
                {
                    OnRestaurantIdChanging(value);
                    ReportPropertyChanging("RestaurantId");
                    _RestaurantId = StructuralObject.SetValidValue(value, "RestaurantId");
                    ReportPropertyChanged("RestaurantId");
                    OnRestaurantIdChanged();
                }
            }
        }
        private global::System.Int32 _RestaurantId;
        partial void OnRestaurantIdChanging(global::System.Int32 value);
        partial void OnRestaurantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RestaurantName
        {
            get
            {
                return _RestaurantName;
            }
            set
            {
                OnRestaurantNameChanging(value);
                ReportPropertyChanging("RestaurantName");
                _RestaurantName = StructuralObject.SetValidValue(value, false, "RestaurantName");
                ReportPropertyChanged("RestaurantName");
                OnRestaurantNameChanged();
            }
        }
        private global::System.String _RestaurantName;
        partial void OnRestaurantNameChanging(global::System.String value);
        partial void OnRestaurantNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false, "Address");
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GPSCoordinate
        {
            get
            {
                return _GPSCoordinate;
            }
            set
            {
                OnGPSCoordinateChanging(value);
                ReportPropertyChanging("GPSCoordinate");
                _GPSCoordinate = StructuralObject.SetValidValue(value, false, "GPSCoordinate");
                ReportPropertyChanged("GPSCoordinate");
                OnGPSCoordinateChanged();
            }
        }
        private global::System.String _GPSCoordinate;
        partial void OnGPSCoordinateChanging(global::System.String value);
        partial void OnGPSCoordinateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseFirst.VirtualChefModel", "FK_Menu_To_Restaurants", "Menu")]
        public EntityCollection<Menu> Menus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Menu>("DatabaseFirst.VirtualChefModel.FK_Menu_To_Restaurants", "Menu");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Menu>("DatabaseFirst.VirtualChefModel.FK_Menu_To_Restaurants", "Menu", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseFirst.VirtualChefModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }

    #endregion

}
